TrajectoryPlannerROS:
  max_vel_x: 0.6
  # min_vel_x: 0.15
  min_vel_x: 0.15 # Allowing velocities too low will will stop the obstacle avoidance because low velocities won't actually be high enough to move the robot
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: false

  # New Stuff

  escape_vel: -0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1  # in rads
  xy_goal_tolerance: 0.2  # in meters
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
    # these parameters change how the planner simulates trajectories at each update and therefore changes the optimal trajectory that is chosen
    # These should be adjusted based on your computer performance
  sim_time: 2.0   # setting time of each simulation that it must evaluate. Higher will create longer curves but too low can limit performance (<2)
  sim_granularity: 0.02 # the step size ...
