#footprint: [[-0.1, -0.15], [-0.1, 0.15], [0.1, 0.15], [0.1, -0.15]]
footprint_padding: 0.2
robot_radius: 0.5

controller_frequency: 15.0
controller_patience: 2.0

planner_frequency: 15.0
planner_patience: 15.0

oscillation_timeout: 1.0
oscillation_distance: 0.1

subscribe_to_updates: true

NavfnROS:
  allow_unknown: true

recovery_behaviors: [
  {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
  {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear:
  reset_distance: 1.5
  #layer_names: ["obstacle_layer"]
aggressive_clear:
  reset_distance: 3.0
  #layer_names: ["obstacle_layer"]