local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  transform_tolerance: 1.0
  update_frequency: 2.0
  publish_frequency: 2.0 
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

  inflater_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 15.0

  obstacle_layer:
    obstacle_range: 15.0
    raytrace_range: 15.0
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {
      sensor_frame: cam_link_optical,
      data_type: PointCloud2,
      topic: planner_cloud,
      expected_update_rate: 6.0,
      marking: true,
      clearing: true,
      min_obstacle_height: -99999,
      max_obstacle_height: 99999}