local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  static_map: true
  rolling_window: false
  width: 4.0
  height: 4.0
  resolution: 0.025
  origin_x: -2.0
  origin_y: -2.0
  
obstacle_layer:
  obstacle_range: 10
  raytrace_range: 11
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {
    sensor_frame: camera_link_optical,
    data_type: PointCloud2, 
    topic: rtabmap/octomap_obstacles,
    expected_update_rate: 1.5, 
    marking: true, 
    clearing: true,
    min_obstacle_height: -99999.0,
    max_obstacle_height: 99999.0}

inflater_layer:
  inflation_radius: 0.05
  cost_scaling_factor: 0.5
  
plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
