protobot_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50  

# parameters for the diff drive controller aka wheel velocity controller.
protobot_velocity_controller: 
  type: "diff_drive_controller/DiffDriveController"
  right_wheel: ['right_front_wheel_pivot', 'right_mid_wheel_pivot', 'right_back_wheel_pivot']
  left_wheel: ['left_front_wheel_pivot', 'left_mid_wheel_pivot', 'left_back_wheel_pivot']
  publish_rate: 50.0
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.50
  wheel_radius: 0.12
  wheel_separation: 1.143
  enable_odom_tf: false
  base_frame_id: base_link

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0




  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           :  2.0  # m/s
      min_velocity           : -2.0 # m/s
      has_acceleration_limits: true
      max_acceleration       :  20.0  # m/s^2
      min_acceleration       : -20.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0  # rad/s^2
   # Base frame_id
   # base_frame_id: base_footprint
   # odom_frame: odom
   # base_link_frame: base_link
   # world_frame: odom 
   #frequency: 50



   #Publish all joint states -----------------------------------
  #joint_state_controller:
    #type: joint_state_controller/JointStateController
    #publish_rate: 50  

  #joint1_velocity_controller:
    #type: velocity_controllers/JointVelocityController
    #joint: right_rear_wheel_joint
    #pid: {p: 100.0, i: 0.01, d: 0.1}
  #joint2_velocity_controller:
    #type: velocity_controllers/JointVelocityController
    #joint: left_rear_wheel_joint
    #pid: {p: 100.0, i: 0.01, d: 0.1}  



