name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    exclude:
    - "/protobot/realsense_ros_gazebo/*.cpp"
    - "/protobot/realsense_ros_gazebo/*.h"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive .
